---
# a version of clickhouse we need
clickhouse_version: "22.3.3.44"

# packages we need for clickhouse installation
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static