apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-deployment
  namespace: 13-kubenet-03-k8sappupdate
spec:
  replicas: 5
  strategy: 
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 80%
  selector:
    matchLabels:
      app: netology-deployment
  template:
    metadata:
      labels:
        app: netology-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.20
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

