apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-deployment
  namespace: 13-kubenet-03-k8sappupdate
spec:
  replicas: 5
  selector:
    matchLabels:
      app: netology-deployment
  template:
    metadata:
      labels:
        app: netology-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: netology-svc
  namespace: 13-kubenet-03-k8sappupdate
spec:
  selector:
    app: netology-deployment
  ports:
  - name: nginx-port
    port: 9001
    targetPort: 80
  - name: multitool-port
    port: 9002
    targetPort: 8080
